### ISSUE TITLE
Repeated 0x2000 in data section.

### ISSUE THREAD

**Issue by zenbooster** [ELEMYO/MYOblue-GUI#1]
Tried reading data from "MYOblue1.0" manually. In some rare but regular cases, a data section may contain a duplicate value of 0x2000. What does this mean?

```
#!/usr/bin/env python3
from struct import *
import time
from datetime import datetime
from enum import IntEnum, auto, unique
import serial

@unique
class ECompressMethod(IntEnum):
    ECM_NONE = 0
    ECM_LZ77 = auto()

s = None
while True:
    try:
        s = serial.Serial('com4', 1000000, timeout=1)
        block = s.read(246)
        if not block:
            print('timeout')
            continue

        length = len(block)
        print(f'len(block={length})')

        utc_time = int(time.time())
        utc = datetime.utcfromtimestamp(utc_time).strftime('%Y-%m-%d %H:%M:%S')
        print("Stream started at {} (UTC)".format(utc))
        
        name = utc
        name = name.replace(' ', '-')
        name = name.replace(':', '-')
        name += '.myoblue.rpd'

        with open(name, 'wb') as f:
            '''
            fmt = '<LLHBBL'
            sig = 0x445052
            ver = 0x0100
            bits_per_sample = 16
            sample_rate = 500
            hdr = pack(fmt, sig, utc_time, ver, ECompressMethod.ECM_NONE, bits_per_sample, sample_rate)
            f.write(hdr)
            '''

            while True:
                '''
                sig = block[:2]
                if sig != b'\xff\xff':
                    raise Exception('Invalid signature!')

                sensor_num = block[2:3][0]
                print('sensor_num = {}'.format(sensor_num))
                msg_num = block[3:6]
                msg_num = msg_num[0] + (msg_num[1] << 8) + (msg_num[2] << 16)
                print('msg_num = {}'.format(msg_num))
                vdd = block[6:8]
                vdd = round((vdd[0] + (vdd[1] << 8)) * 0.6/16384*6*2, 2)
                print('battery charge = {}'.format(vdd))
                
                block = block[8:] # оставляем только данные
                '''
                f.write(block)
                
                block = s.read(246)
                if not block:
                    print('timeout')
                    break

                length = len(block)
                print(f'len(block={length})')

        print("Stream ended")

    except Exception as e:
        print('Exception: {}'.format(str(e)))
        s = None
        time.sleep(1)
```

`0000014B6C:

0000014B7C: ?? ?? ?? ?? ?? ?? ?? ?? | ?? ?? FF FF 01 08 04 00  ©♥ґ♥·♥Ѕ♥Б♥яя☺◘♦
0000014B8C: F2 18 C7 03 CB 03 D0 03 │ D5 03 D5 03 FA 02 BC 13  т↑З♥Л♥Р♥Х♥Х♥ъ☻ј‼
0000014B9C: 55 3B C1 3C ED 3C EF 3C │ EE 3C EC 3C E1 3C D7 3C  U;Б<н<п<о<м<б<Ч<
0000014BAC: D0 3C CB 3C BF 3C B3 3C │ A8 3C 8B 3C E7 14 AE 02  Р<Л<ї<і<Ё<‹<з¶®☻
0000014BBC: 7F 02 84 02 8E 02 99 02 │ 9F 02 A9 02 B3 02 B8 02  ⌂☻„☻Ћ☻™☻џ☻©☻і☻ё☻
0000014BCC: C4 02 C9 02 D1 02 D3 02 │ 3C 02 A2 02 92 2D 52 3C  Д☻Й☻С☻У☻<☻ў☻’-R<
0000014BDC: E2 3C ED 3C E8 3C E1 3C │ D4 3C CB 3C C2 3C B9 3C  в<н<и<б<Ф<Л<В<№<
0000014BEC: AE 3C 9E 3C 8A 3C 6D 3C │ 31 3C 39 3C 1F 3C FD 3B  ®<ћ<Љ<m<1<9<▼<э;
0000014BFC: D0 3B 38 2C D4 02 E7 01 │ ED 01 F9 01 FF 01 0C 02  Р;8,Ф☻з☺н☺щ☺я☺♀☻
0000014C0C: 1A 02 20 02 FD 01 5C 02 │ 4F 02 51 02 5A 02 66 02  →☻ ☻э☺\☻O☻Q☻Z☻f☻
0000014C1C: 6E 02 79 02 84 02 8A 02 │ 93 02 9F 02 A7 02 B0 02  n☻y☻„☻Љ☻“☻џ☻§☻°☻
0000014C2C: B9 02 8E 02 F8 02 F3 02 │ E0 02 E4 02 EC 02 F3 02  №☻Ћ☻ш☻у☻а☻д☻м☻у☻
0000014C3C: F8 02 02 03 0A 03 13 03 │ 1A 03 1F 03 25 03 2E 03  ш☻☻♥◙♥‼♥→♥▼♥%♥.♥ 
0000014C4C: 18 03 52 03 53 03 4B 03 │ 52 03 58 03 5F 03 64 03  ↑♥R♥S♥K♥R♥X♥_♥d♥
0000014C5C: 67 03 6C 03 74 03 7C 03 │ 84 03 88 03 8F 03 8D 03  g♥l♥t♥|♥„♥€♥Џ♥Ќ♥
0000014C6C: A8 03 BF 03 AA 03 A7 03 │ AD 03 B2 03 B9 03 BB 03  Ё♥ї♥Є♥§♥­♥І♥№♥»♥
0000014C7C: FF FF 01 09 04 00 EC 18 │ 00 20 00 20 00 20 00 20  яя☺○♦ м↑
0000014C8C: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014C9C: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014CAC: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014CBC: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014CCC: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014CDC: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014CEC: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014CFC: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014D0C: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014D1C: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014D2C: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014D3C: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014D4C: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014D5C: 00 20 00 20 00 20 00 20 │ 00 20 00 20 00 20 00 20
0000014D6C: 00 20 00 20 00 20 FF FF │ 01 0A 04 00 EC 18 54 03        яя☺◙♦ м↑T♥
0000014D7C: 5A 03 5E 03 65 03 6E 03 │ 74 03 7B 03 7F 03 81 03  Z♥^♥e♥n♥t♥{♥⌂♥Ѓ♥
0000014D8C: 87 03 8A 03 A4 02 C1 18 │ A9 3B C5 3C E3 3C E0 3C  ‡♥Љ♥¤☻Б↑©;Е<г<а<
0000014D9C: DF 3C DA 3C D3 3C D0 3C │ CB 3C C1 3C B4 3C A5 3C  Я<Ъ<У<Р<Л<Б<ґ<Ґ<
0000014DAC: 95 3C 63 3C 5C 3C 51 3C │ 42 3C 24 3C FC 3B C2 3B  •<c<\<Q<B<$<ь;В;
0000014DBC: FB 1E 93 02 39 02 3D 02 │ 47 02 51 02 5B 02 5F 02  ы▲“☻9☻=☻G☻Q☻[☻_☻
0000014DCC: 41 02 94 02 89 02 8D 02 │ 96 02 A0 02 A8 02 B2 02  A☻”☻‰☻Ќ☻–☻ ☻Ё☻І☻
0000014DDC: BC 02 C3 02 CA 02 D4 02 │ DC 02 E2 02 E9 02 C7 02  ј☻Г☻К☻Ф☻Ь☻в☻й☻З☻
0000014DEC: 26 03 11 03 0B 03 14 03 │ 18 03 24 03 27 03 34 03  &♥◄♥♂♥¶♥↑♥$♥'♥4♥
0000014DFC: 39 03 42 03 47 03 4D 03 │ 52 03 54 03 2F 03 99 03  9♥B♥G♥M♥R♥T♥/♥™♥
0000014E0C: 7B 03 73 03 76 03 7D 03 │ 83 03 88 03 92 03 97 03  {♥s♥v♥}♥ѓ♥€♥’♥—♥
0000014E1C: 99 03 A1 03 A6 03 AB 03 │ AC 03 82 03 EE 03 D5 03  ™♥Ў♥¦♥«♥¬♥‚♥о♥Х♥
0000014E2C: C4 03 C6 03 CB 03 D4 03 │ D8 03 DD 03 E1 03 E5 03  Д♥Ж♥Л♥Ф♥Ш♥Э♥б♥е♥
0000014E3C: E8 03 EF 03 F2 03 F0 03 │ C5 03 3C 04 25 04 07 04  и♥п♥т♥р♥Е♥<♦%♦•♦
0000014E4C: 07 04 0D 04 11 04 15 04 │ 1C 04 1E 04 21 04 28 04  •♦♪♦◄♦§♦∟♦▲♦!♦(♦
0000014E5C: 2B 04 2E 04 30 04 15 04 │ 67 04 6A 04 `

**Comment by ELEMYO** [comment]
Hello, 

Do you mean repeated data in one message (119 data points - 1904 bits)? It caused by next specific of sensor: sensor has only one ADC, and one time per minute sensor changes sampling channel from EMG/ECG to battery for measuring battery level. It makes one non-informable message per minute: the data in this message is the reference value of EMG/ECG signal. The time period between data points in this message is the same with other messages, so it doesn’t influence to sensor EMG/ECG signal timing.

**Comment by zenbooster** [comment]
Now I understand, thanks.
